import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'Disclaimer — IQ Platform',
  description: 'Disclaimer for IQ Platform. Important information about the nature of our cognitive assessment.',
}

export default function Disclaimer() {
  return (
    <div style={{ minHeight: '100vh', background: '#0a0f1e' }}>
      <Navbar />
      <main style={{ maxWidth: 720, margin: '0 auto', padding: '48px 20px 80px' }}>

        <div style={{ marginBottom: 40 }}>
          <span style={{
            fontSize: 11, fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase',
            color: '#6366f1', background: 'rgba(99,102,241,0.1)', padding: '4px 12px', borderRadius: 20,
          }}>Legal</span>
          <h1 style={{ fontSize: 32, fontWeight: 700, color: '#e2e8f0', marginTop: 16, marginBottom: 8 }}>
            Disclaimer
          </h1>
          <p style={{ fontSize: 14, color: '#475569' }}>Last updated: June 2025</p>
        </div>

        {/* Important notice banner */}
        <div style={{
          padding: '20px 24px', borderRadius: 14, marginBottom: 28,
          background: 'rgba(251,191,36,0.07)', border: '1px solid rgba(251,191,36,0.2)',
        }}>
          <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
            <span style={{ fontSize: 24, flexShrink: 0 }}>⚠️</span>
            <div>
              <h2 style={{ fontSize: 15, fontWeight: 600, color: '#fbbf24', marginBottom: 6 }}>Important Notice</h2>
              <p style={{ fontSize: 13, color: '#92400e', lineHeight: 1.7, margin: 0 }}>
                IQ Platform is an educational and entertainment tool only. The scores produced are <strong>not clinically validated</strong> and should not be used for any diagnostic, medical, educational placement, employment, or professional assessment purpose.
              </p>
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>

          <Section title="1. Not a Clinical Assessment">
            <p>The IQ scores produced by IQ Platform are generated by a proprietary machine learning algorithm that considers multiple performance factors. However, this platform is <strong style={{ color: '#e2e8f0' }}>not</strong> a standardised, normed, or clinically validated psychometric instrument.</p>
            <p>Official IQ assessments (such as the WAIS, Stanford-Binet, or WISC) are administered by licensed psychologists under controlled conditions with large normative samples. IQ Platform cannot replicate or substitute for these assessments.</p>
          </Section>

          <Section title="2. Results Are Estimates Only">
            <p>Any IQ score, percentile, or cognitive classification displayed on this platform is an estimate for informational and recreational purposes only. Results may vary between sessions due to:</p>
            <ul>
              <li>Random question selection from our question pool.</li>
              <li>Variations in your concentration, mood, or environment at the time of testing.</li>
              <li>The inherent limitations of an online, unsupervised testing environment.</li>
              <li>The fact that our question bank, while diverse, cannot cover all aspects of human intelligence.</li>
            </ul>
          </Section>

          <Section title="3. Not Medical or Psychological Advice">
            <p>Nothing on IQ Platform constitutes medical, psychological, or professional advice. If you have concerns about cognitive function, learning disabilities, neurodevelopmental conditions, or mental health, please consult a licensed medical or psychological professional.</p>
          </Section>

          <Section title="4. Not for Professional Use">
            <p>Results from IQ Platform must not be used for:</p>
            <ul>
              <li>Academic placement or school admission decisions.</li>
              <li>Employment screening or hiring decisions.</li>
              <li>Clinical diagnosis of any condition.</li>
              <li>Legal proceedings or official documentation.</li>
              <li>Any purpose requiring a validated psychological assessment.</li>
            </ul>
          </Section>

          <Section title="5. Third-Party Advertising">
            <p>IQ Platform displays third-party advertisements served by Google AdSense and potentially other advertising networks. We do not endorse, verify, or take responsibility for the accuracy, safety, or appropriateness of any advertised products or services. Clicking on advertisements is done at your own risk.</p>
          </Section>

          <Section title="6. Accuracy of Information">
            <p>While we make every effort to ensure that questions and information on this platform are accurate, we make no guarantees regarding the completeness, correctness, or currency of any content. The ML scoring algorithm is our own implementation and may produce results that differ from other IQ assessments.</p>
          </Section>

          <Section title="7. External Links">
            <p>IQ Platform may contain links to third-party websites. These links are provided for convenience only. We have no control over the content of those sites and accept no responsibility for them or for any loss or damage that may arise from your use of them.</p>
          </Section>

          <Section title="8. Changes to This Disclaimer">
            <p>We reserve the right to update this Disclaimer at any time. Continued use of the platform after any changes constitutes acceptance of the updated Disclaimer.</p>
          </Section>

          <Section title="9. Contact">
            <p>If you have questions about this Disclaimer, please contact us via our <a href="/contact" style={{ color: '#818cf8' }}>Contact page</a>.</p>
          </Section>

        </div>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{
      padding: '22px 26px', borderRadius: 14,
      background: 'rgba(17,24,39,0.7)', border: '1px solid rgba(99,102,241,0.1)',
    }}>
      <h2 style={{ fontSize: 16, fontWeight: 600, color: '#c7d2fe', marginBottom: 12 }}>{title}</h2>
      <div style={{ fontSize: 14, color: '#64748b', lineHeight: 1.8, display: 'flex', flexDirection: 'column', gap: 8 }}>
        {children}
      </div>
    </section>
  )
}
